// Generated by design/tokens/generate-android-theme.mjs from design/tokens/tokens.json
// and design/tokens/generated/color-scheme.json — do not hand-edit, re-run the generator instead.

package `in`.chetna.mobile.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

fun chetnaLightColorScheme(): ColorScheme {
    return lightColorScheme(
        primary = Color(0xFF6151A6),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE6DEFF),
        onPrimaryContainer = Color(0xFF1D0160),
        secondary = Color(0xFF605B71),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE6DFF9),
        onSecondaryContainer = Color(0xFF1C192B),
        tertiary = Color(0xFF7C5263),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD9E5),
        onTertiaryContainer = Color(0xFF30111F),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFFBFF),
        onBackground = Color(0xFF1C1B1E),
        surface = Color(0xFFFFFBFF),
        onSurface = Color(0xFF1C1B1E),
        surfaceVariant = Color(0xFFE6E0EC),
        onSurfaceVariant = Color(0xFF48454E),
        outline = Color(0xFF79757F),
        outlineVariant = Color(0xFFC9C4D0),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF313033),
        inverseOnSurface = Color(0xFFF4EFF4),
        inversePrimary = Color(0xFFCBBEFF),
    )
}

fun chetnaDarkColorScheme(): ColorScheme {
    return darkColorScheme(
        primary = Color(0xFFCBBEFF),
        onPrimary = Color(0xFF322074),
        primaryContainer = Color(0xFF49398C),
        onPrimaryContainer = Color(0xFFE6DEFF),
        secondary = Color(0xFFCAC3DC),
        onSecondary = Color(0xFF322E41),
        secondaryContainer = Color(0xFF484458),
        onSecondaryContainer = Color(0xFFE6DFF9),
        tertiary = Color(0xFFEDB8CB),
        onTertiary = Color(0xFF492535),
        tertiaryContainer = Color(0xFF623B4B),
        onTertiaryContainer = Color(0xFFFFD9E5),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFB4AB),
        background = Color(0xFF1C1B1E),
        onBackground = Color(0xFFE6E1E6),
        surface = Color(0xFF1C1B1E),
        onSurface = Color(0xFFE6E1E6),
        surfaceVariant = Color(0xFF48454E),
        onSurfaceVariant = Color(0xFFC9C4D0),
        outline = Color(0xFF938F99),
        outlineVariant = Color(0xFF48454E),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE6E1E6),
        inverseOnSurface = Color(0xFF313033),
        inversePrimary = Color(0xFF6151A6),
    )
}
