// Generated by design/tokens/generate-android-theme.mjs from design/tokens/tokens.json
// and design/tokens/generated/color-scheme.json — do not hand-edit, re-run the generator instead.

package `in`.chetna.mobile.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.unit.dp

val BezelShape = RoundedCornerShape(22.dp)
val CardShape = RoundedCornerShape(14.dp)
val ButtonShape = RoundedCornerShape(20.dp)
val RowShape = RoundedCornerShape(10.dp)
